replicaCount: 1

image:
  repository: starwitorg/sbom-generator
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

app:
  context_path: ""

auth:
  enabled: false
  jwt_jwk_set_uri: "http://hostname/realms/realmname/protocol/openid-connect/certs" # sets spring.security.oauth2.resourceserver.jwt.jwk-set-uri
  jwt_issuer_uri: "http://hostname/realms/realmname" # sets spring.security.oauth2.resourceserver.jwt.issuer-uri
  keycloak_issuer_uri: "http://hostname/realms/realmname" # sets spring.security.oauth2.client.provider.keycloak.issuer-uri

service:
  port: 8080

# extraEnv: |
#   - name: JAVA_TOOL_OPTIONS
#     value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000
#   - name: LOGGING_LEVEL_ROOT
#     value: DEBUG

autoscaling:
  enabled: false